name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product is this feature for?
      options:
        - Web Dashboard
        - Discord Bot
        - Twitch Bot
        - Public API
        - Cross-Platform (ban sync, account linking, etc.)
        - New Product / General
    validations:
      required: true

  - type: dropdown
    id: feature
    attributes:
      label: Feature Area
      description: Which area does this relate to?
      options:
        - AutoMod / Spam Filtering
        - Moderation (strikes, bans, mod queue)
        - XP / Reputation / Leaderboards
        - Raid Detection
        - Appeals
        - Custom Commands
        - Automation Engine
        - Roles / Rewards
        - Timed Messages
        - Billing / Subscriptions
        - Webhooks / API Keys
        - Authentication / Login
        - New Feature Area
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like to see
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would this feature help you?
      placeholder: This would help me...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions?
      placeholder: I've also thought about...
    validations:
      required: false
